### ISSUE TITLE
Remove button not working on Demo

### ISSUE THREAD

**Issue by 3lvis** [stevestreza/Relayout#1]
![simulator screen shot aug 4 2016 6 56 40 pm](https://cloud.githubusercontent.com/assets/1088217/17410715/2fb754a8-5a75-11e6-86db-b80709dd7c1e.png)

**Comment by stevestreza** [comment]
I'm going to remove the "Remove" button and make clicking the buttons remove them.

**Comment by 3lvis** [comment]
Awesome! Even better :)
